In [ ]:
#Practice module 7 material

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn

%matplotlib inline

In [7]:
location = "datasets/datasets/DC_Properties.csv"
df = pd.read_csv(location)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [9]:
#show the column names in the dataset
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [10]:
#show the data type of each column
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [11]:
#number of non-NA values
df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [29]:
dupe = df.duplicated() #creates list of True/False values
df[dupe] #shows rows where duplicated is True

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [30]:
#drops duplicate rows, default is to keep first observation
df.drop_duplicates()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [47]:
#Create a new dataframe with only the data that I want to consider 
df2 = df[["PRICE","ROOMS","BEDRM","BATHRM","HF_BATHRM","KITCHENS","NUM_UNITS","SALE_NUM","GBA","AYB","ZIPCODE","LATITUDE","LONGITUDE"]]
df2.head()

,PRICE,ROOMS,BEDRM,BATHRM,HF_BATHRM,KITCHENS,NUM_UNITS,SALE_NUM,GBA,AYB,ZIPCODE,LATITUDE,LONGITUDE
0,1095000.0,8,4,4,0,2.0,2.0,1,2522.0,1910.0,20009.0,38.914680,-77.040832
1,NaN,11,5,3,1,2.0,2.0,1,2567.0,1898.0,20009.0,38.914683,-77.040764
2,2100000.0,9,5,3,1,2.0,2.0,3,2522.0,1910.0,20009.0,38.914684,-77.040678
3,1602000.0,8,5,3,1,2.0,2.0,1,2484.0,1900.0,20009.0,38.914683,-77.040629
4,NaN,11,3,2,1,1.0,1.0,1,5255.0,1913.0,20009.0,38.914383,-77.039361

In [ ]:
# Check for missing data in your dependent variable; drop rows with missing data in your dependent variable

In [69]:
df_no_missing = df.dtypes

In [70]:
#drop rows with any missing data
df_no_missing = df.dropna()
df_no_missing

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [59]:
dupe = df2.duplicated() #creates list of True/False values
df[dupe] #shows rows where duplicated is True

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
9050,9050,1,0,Forced Air,Y,1.0,4,2,1890.0,2001.0,...,-77.001350,Capitol Hill,009 C Capitol Hill,8200.0,008200 2017,Ward 6,786,-77.001352,38.890489,NE
18287,18287,1,0,Hot Water Rad,N,1.0,6,2,1890.0,1975.0,...,-77.071395,Georgetown,025 B Georgetown,202.0,000202 4005,Ward 2,1223,-77.071002,38.906270,NW
20204,20204,1,1,Gravity Furnac,N,1.0,6,3,1900.0,NaN,...,-77.070674,Georgetown,025 B Georgetown,202.0,000202 4001,Ward 2,1248,-77.070752,38.908106,NW
25807,25807,0,0,Hot Water Rad,N,0.0,0,0,1984.0,NaN,...,-77.097720,Kent,030 C Kent,902.0,NaN,Ward 3,1409,-77.097722,38.926143,NW
31975,31975,2,1,Warm Cool,Y,1.0,6,3,1985.0,NaN,...,-77.073665,Chevy Chase,011 A Chevy Chase,1100.0,NaN,Ward 3,1872,-77.073667,38.960514,NW
75079,75079,4,0,Hot Water Rad,N,4.0,16,4,1932.0,NaN,...,-76.984640,Trinidad,052 B Trinidad,8802.0,NaN,Ward 5,4062,-76.984643,38.903371,NE
82988,82988,3,1,Forced Air,Y,1.0,6,3,2014.0,NaN,...,-76.950931,Lily Ponds,032 B Lily Ponds,9602.0,NaN,Ward 7,5039,-76.950933,38.902755,NE
83556,83556,3,0,Forced Air,Y,1.0,6,3,2014.0,NaN,...,-76.950931,Lily Ponds,032 B Lily Ponds,9602.0,NaN,Ward 7,5039,-76.950933,38.902755,NE
92494,92494,3,1,Forced Air,Y,1.0,8,5,2017.0,NaN,...,-76.929480,Marshall Heights,033 A Marshall Heights,9904.0,NaN,Ward 7,5324,-76.929482,38.885453,SE
98932,98932,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.979472,Randle Heights,043 D Randle Heights,7404.0,007404 1006,Ward 8,5881,-76.978771,38.850426,SE
98933,98933,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.979472,Randle Heights,043 D Randle Heights,7404.0,007404 1006,Ward 8,5881,-76.978771,38.850426,SE
98934,98934,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.979472,Randle Heights,043 D Randle Heights,7404.0,007404 1006,Ward 8,5881,-76.978771,38.850426,SE
98935,98935,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.979472,Randle Heights,043 D Randle Heights,7404.0,007404 1006,Ward 8,5881,-76.978771,38.850426,SE
101278,101278,2,0,Forced Air,Y,2.0,6,2,2008.0,NaN,...,-76.981782,Randle Heights,043 D Randle Heights,7404.0,007404 2004,Ward 8,5890,-76.981790,38.848253,SE
101279,101279,2,0,Forced Air,Y,2.0,6,2,2008.0,NaN,...,-76.981782,Randle Heights,043 D Randle Heights,7404.0,007404 2004,Ward 8,5890,-76.981790,38.848253,SE
101389,101389,2,0,Forced Air,Y,2.0,6,2,2008.0,NaN,...,-76.981802,Randle Heights,043 D Randle Heights,7404.0,007404 2004,Ward 8,5890,-76.981790,38.848253,SE
101708,101708,2,0,Forced Air,Y,2.0,6,2,2008.0,NaN,...,-76.981802,Randle Heights,043 D Randle Heights,7404.0,007404 2004,Ward 8,5890,-76.981790,38.848253,SE
101709,101709,2,0,Forced Air,Y,2.0,6,2,2008.0,NaN,...,-76.981802,Randle Heights,043 D Randle Heights,7404.0,007404 2004,Ward 8,5890,-76.981790,38.848253,SE
101832,101832,2,0,Forced Air,Y,2.0,5,2,2007.0,NaN,...,-76.981557,Randle Heights,043 D Randle Heights,7404.0,007404 2005,Ward 8,5890,-76.981790,38.848253,SE
101833,101833,2,0,Forced Air,Y,2.0,5,2,2007.0,NaN,...,-76.981557,Randle Heights,043 D Randle Heights,7404.0,007404 2005,Ward 8,5890,-76.981790,38.848253,SE
101834,101834,2,0,Forced Air,Y,2.0,5,2,2007.0,NaN,...,-76.981557,Randle Heights,043 D Randle Heights,7404.0,007404 2005,Ward 8,5890,-76.981790,38.848253,SE
102747,102747,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.980116,Randle Heights,043 D Randle Heights,7404.0,007404 1010,Ward 8,5883,-76.980110,38.849663,SE
102748,102748,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.980116,Randle Heights,043 D Randle Heights,7404.0,007404 1010,Ward 8,5883,-76.980110,38.849663,SE
102749,102749,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.980116,Randle Heights,043 D Randle Heights,7404.0,007404 1010,Ward 8,5883,-76.980110,38.849663,SE
102750,102750,2,0,Warm Cool,Y,2.0,6,2,2005.0,NaN,...,-76.980116,Randle Heights,043 D Randle Heights,7404.0,007404 1010,Ward 8,5883,-76.980110,38.849663,SE
106671,106671,2,0,Hot Water Rad,N,2.0,4,2,1951.0,NaN,...,-76.997694,Congress Heights,016 C Congress Heights,9811.0,009811 2004,Ward 8,6250,-76.997266,38.824946,SE
106713,106713,2,0,Forced Air,Y,NaN,4,2,2007.0,NaN,...,-77.010407,Chillum,NaN,2102.0,NaN,Ward 4,3393,-77.010410,38.955767,NW
106715,106715,1,0,Ht Pump,Y,NaN,4,2,1937.0,2009.0,...,-77.012602,Petworth,042 C Petworth,2102.0,NaN,Ward 4,3399,-77.012605,38.952882,NW
106716,106716,1,0,Ht Pump,Y,NaN,4,2,1937.0,2009.0,...,-77.012602,Petworth,042 C Petworth,2102.0,NaN,Ward 4,3399,-77.012605,38.952882,NW
106717,106717,1,0,Ht Pump,Y,NaN,4,2,1937.0,2009.0,...,-77.012602,Petworth,042 C Petworth,2102.0,NaN,Ward 4,3399,-77.012605,38.952882,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158837,158837,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158840,158840,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158842,158842,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158847,158847,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158848,158848,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158849,158849,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158850,158850,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158852,158852,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158856,158856,1,0,Warm Cool,Y,NaN,2,0,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158857,158857,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158859,158859,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158860,158860,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158862,158862,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158863,158863,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158865,158865,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158866,158866,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158872,158872,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158879,158879,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158883,158883,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158887,158887,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158889,158889,1,0,Forced Air,Y,NaN,4,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158890,158890,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158895,158895,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158896,158896,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158898,158898,2,0,Ht Pump,Y,NaN,4,2,2004.0,2004.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158917,158917,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158925,158925,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [60]:
#drops duplicate rows, default is to keep first observation
df2.drop_duplicates()

,PRICE,ROOMS,BEDRM,BATHRM,HF_BATHRM,KITCHENS,NUM_UNITS,SALE_NUM,GBA,AYB,ZIPCODE,LATITUDE,LONGITUDE
0,1095000.0,8,4,4,0,2.0,2.0,1,2522.0,1910.0,20009.0,38.914680,-77.040832
1,NaN,11,5,3,1,2.0,2.0,1,2567.0,1898.0,20009.0,38.914683,-77.040764
2,2100000.0,9,5,3,1,2.0,2.0,3,2522.0,1910.0,20009.0,38.914684,-77.040678
3,1602000.0,8,5,3,1,2.0,2.0,1,2484.0,1900.0,20009.0,38.914683,-77.040629
4,NaN,11,3,2,1,1.0,1.0,1,5255.0,1913.0,20009.0,38.914383,-77.039361
5,1950000.0,10,5,3,2,1.0,1.0,1,5344.0,1913.0,20009.0,38.914331,-77.039715
6,NaN,5,2,1,0,2.0,2.0,1,1260.0,1917.0,20009.0,38.914983,-77.041055
7,1050000.0,8,4,3,1,2.0,2.0,1,2401.0,1906.0,20009.0,38.915408,-77.040129
8,1430000.0,7,3,3,1,2.0,2.0,4,1488.0,1908.0,20009.0,38.915017,-77.039903
9,NaN,6,2,1,1,1.0,1.0,1,1590.0,1908.0,20009.0,38.915015,-77.040081
10,NaN,12,5,3,0,3.0,3.0,1,2748.0,1890.0,20009.0,38.914980,-77.040760
11,NaN,16,6,5,0,3.0,3.0,1,3100.0,1905.0,20009.0,38.915363,-77.039718
12,NaN,9,5,2,0,2.0,2.0,1,3119.0,1894.0,20009.0,38.914999,-77.039569
13,NaN,11,5,2,0,2.0,2.0,1,3044.0,1885.0,20009.0,38.914997,-77.039644
14,1325000.0,5,3,3,1,2.0,2.0,1,2692.0,1917.0,20009.0,38.915038,-77.039716
15,NaN,9,4,2,1,2.0,2.0,1,1662.0,1908.0,20009.0,38.915019,-77.039784
16,1240000.0,8,3,3,1,1.0,1.0,1,1662.0,1908.0,20009.0,38.915018,-77.039844
17,NaN,6,3,2,0,1.0,1.0,1,1542.0,1908.0,20009.0,38.915017,-77.039961
18,NaN,10,4,3,1,2.0,2.0,6,1542.0,1908.0,20009.0,38.915016,-77.040020
19,592250.0,9,3,3,1,2.0,2.0,1,1598.0,1908.0,20009.0,38.915019,-77.040138
20,33232.0,14,5,3,1,1.0,1.0,3,3465.0,1880.0,20009.0,38.911370,-77.033774
21,NaN,12,3,3,0,2.0,2.0,4,2912.0,1880.0,20009.0,38.911368,-77.033838
22,907400.0,6,3,1,0,1.0,1.0,1,1790.0,1880.0,20009.0,38.911368,-77.033925
23,1065000.0,5,3,2,1,1.0,1.0,1,1600.0,1880.0,20009.0,38.911368,-77.033972
24,1100000.0,8,3,2,1,1.0,1.0,1,1958.0,1880.0,20009.0,38.911319,-77.034070
25,20000.0,8,4,1,0,1.0,1.0,1,2099.0,1880.0,20009.0,38.911337,-77.034156
26,NaN,10,5,1,0,1.0,1.0,1,2478.0,1900.0,20009.0,38.911736,-77.034258
27,703700.0,9,3,3,0,4.0,4.0,1,2520.0,1900.0,20009.0,38.911732,-77.034182
28,NaN,10,4,3,0,2.0,2.0,3,3610.0,1900.0,20009.0,38.911677,-77.034119
29,1210000.0,11,3,3,1,2.0,2.0,1,2520.0,1900.0,20009.0,38.911699,-77.034051
...,...,...,...,...,...,...,...,...,...,...,...,...,...
158923,NaN,6,3,2,0,NaN,NaN,1,NaN,1993.0,20001.0,38.914279,-77.019274
158924,269000.0,5,2,1,0,NaN,NaN,1,NaN,1993.0,20001.0,38.914279,-77.019274
158926,385000.0,5,2,1,0,NaN,NaN,2,NaN,1993.0,20001.0,38.914279,-77.019274
158927,NaN,6,3,2,0,NaN,NaN,2,NaN,1993.0,20001.0,38.914279,-77.019274
158928,632400.0,5,2,2,1,NaN,NaN,3,NaN,2013.0,20001.0,38.914279,-77.019274
158929,574000.0,5,2,2,1,NaN,NaN,1,NaN,2013.0,20001.0,38.914279,-77.019274
158930,365000.0,4,2,2,0,NaN,NaN,1,NaN,1900.0,20001.0,38.912947,-77.019243
158931,405000.0,4,2,2,1,NaN,NaN,1,NaN,1900.0,20001.0,38.912947,-77.019243
158932,505000.0,4,2,2,1,NaN,NaN,3,NaN,1900.0,20001.0,38.912947,-77.019243
158933,520000.0,4,2,2,0,NaN,NaN,2,NaN,1880.0,20001.0,38.912947,-77.019243
158934,499900.0,3,1,1,1,NaN,NaN,2,NaN,1880.0,20001.0,38.912947,-77.019243
158935,451000.0,3,1,1,0,NaN,NaN,2,NaN,1880.0,20001.0,38.912947,-77.019243
158936,564900.0,3,1,1,0,NaN,NaN,2,NaN,1880.0,20001.0,38.912947,-77.019243
158937,NaN,4,2,1,0,NaN,NaN,1,NaN,1992.0,20001.0,38.911840,-77.019420
158938,660000.0,7,4,2,0,NaN,NaN,3,NaN,1992.0,20001.0,38.911840,-77.019420
158939,380000.0,4,2,1,0,NaN,NaN,2,NaN,1992.0,20001.0,38.911840,-77.019420
158940,NaN,7,4,2,0,NaN,NaN,1,NaN,1992.0,20001.0,38.911840,-77.019420
158943,539000.0,5,2,2,1,NaN,NaN,1,NaN,2004.0,20001.0,38.911840,-77.019420
158944,908500.0,5,2,2,1,NaN,NaN,4,NaN,2004.0,20001.0,38.911840,-77.019420
158945,450000.0,3,1,1,0,NaN,NaN,1,NaN,1938.0,20001.0,38.911840,-77.019420
158946,485355.0,4,2,1,0,NaN,NaN,4,NaN,1938.0,20001.0,38.911840,-77.019420
158947,320000.0,4,2,2,0,NaN,NaN,1,NaN,1938.0,20001.0,38.911840,-77.019420
158948,460000.0,4,2,2,0,NaN,NaN,1,NaN,1938.0,20001.0,38.911840,-77.019420
158949,550000.0,4,1,1,1,NaN,NaN,6,NaN,1938.0,20001.0,38.911840,-77.019420
158950,635000.0,5,3,3,0,NaN,NaN,5,NaN,1938.0,20001.0,38.911840,-77.019420
158951,389000.0,5,3,3,1,NaN,NaN,1,NaN,1938.0,20001.0,38.911840,-77.019420
158952,399900.0,3,1,1,0,NaN,NaN,4,NaN,1938.0,20001.0,38.911840,-77.019420
158953,416000.0,4,2,1,0,NaN,NaN,1,NaN,1938.0,20001.0,38.911840,-77.019420
158954,600000.0,4,2,2,0,NaN,NaN,1,NaN,1920.0,20001.0,38.911840,-77.019420
158955,215100.0,2,0,1,0,NaN,NaN,3,NaN,1965.0,20024.0,38.872953,-77.018230

In [61]:
from sklearn.linear_model import LinearRegression

X = df2.drop('PRICE', axis = 1)
price = df2[['PRICE']]

In [62]:
X.head()

,ROOMS,BEDRM,BATHRM,HF_BATHRM,KITCHENS,NUM_UNITS,SALE_NUM,GBA,AYB,ZIPCODE,LATITUDE,LONGITUDE
0,8,4,4,0,2.0,2.0,1,2522.0,1910.0,20009.0,38.914680,-77.040832
1,11,5,3,1,2.0,2.0,1,2567.0,1898.0,20009.0,38.914683,-77.040764
2,9,5,3,1,2.0,2.0,3,2522.0,1910.0,20009.0,38.914684,-77.040678
3,8,5,3,1,2.0,2.0,1,2484.0,1900.0,20009.0,38.914683,-77.040629
4,11,3,2,1,1.0,1.0,1,5255.0,1913.0,20009.0,38.914383,-77.039361

In [63]:
price.head()

       PRICE
0  1095000.0
1        NaN
2  2100000.0
3  1602000.0
4        NaN

In [64]:
#assign linear regression function to a variable
lm = LinearRegression()
lm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

#### Important functions to keep in mind while fitting a linear regression model are:

â€¢lm.fit() -> fits a linear model 


â€¢lm.predict() -> Predict Y using the linear model with estimated coefficients 


â€¢lm.score() -> Returns the coefficient of determination (R^2). A measure of how well observed outcomes are replicated by the model, as the proportion of total variation of outcomes explained by the model.

In [65]:
lm.fit(X, price)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [56]:
lm.fit(X, PRICE)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [57]:
print('Estimated intercept coefficient:', lm.intercept_)

AttributeError: 'LinearRegression' object has no attribute 'intercept_'